# Generated by Django 6.1.1 on 2026-09-11 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('license_no', models.CharField(blank=True, max_length=50)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('reserves_tons', models.DecimalField(decimal_places=2, default=0, help_text='Estimated reserves in tons', max_digits=14)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=20)),
                ('coal_type', models.CharField(choices=[('Anthracite', 'Anthracite'), ('Bituminous', 'Bituminous'), ('Sub-bituminous', 'Sub-bituminous'), ('Lignite', 'Lignite')], default='Bituminous', max_length=30)),
                ('quantity_tons', models.DecimalField(decimal_places=2, help_text='Coal produced in tons', max_digits=12)),
                ('overburden_removed', models.DecimalField(decimal_places=2, default=0, help_text='Waste removed in tons', max_digits=12)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('workers_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='employees.mine')),
            ],
            options={
                'ordering': ['-date', 'shift'],
            },
        ),
    ]
