# Generated by Django 6.1.1 on 2026-09-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Spare Part', 'Spare Part'), ('Fuel', 'Fuel'), ('Explosive', 'Explosive'), ('Safety Gear', 'Safety Gear'), ('Consumable', 'Consumable'), ('Other', 'Other')], default='Spare Part', max_length=30)),
                ('unit', models.CharField(default='pcs', help_text='e.g. pcs, kg, liter, box', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when quantity falls below this', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, help_text='Storage location', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], default='IN', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, help_text='e.g. purchase, issued to mine, damaged', max_length=200)),
                ('handled_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.inventoryitem')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
