# Generated by Django 6.1.1 on 2026-09-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_customer_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_check_in',
            field=models.BooleanField(default=True, help_text='Auto-filled on save'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='auto_check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_reason',
            field=models.TextField(blank=True, help_text='Reason if status is Leave'),
        ),
    ]
