# Generated by Django 6.1.1 on 2026-09-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_added_by_employee_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, help_text='Real-time photo at check-in', null=True, upload_to='attendance/'),
        ),
    ]
