# Generated by Django 6.1.1 on 2026-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_attendance_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo_out',
            field=models.ImageField(blank=True, help_text='Photo at check-out', null=True, upload_to='attendance/out/'),
        ),
    ]
