# Generated by Django 6.1.1 on 2026-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_attendance_photo_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Info', 'Info'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Info', max_length=20),
        ),
    ]
